export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_ACTIVITIES = "CLEAR_ACTIVITIES";
export const GET_GROUP_TYPES = "GET_GROUP_TYPES";
export const GET_CATEGORIES = "GET_CATEGORIES";
